version: "3.9"

services:
  runner-task:
    build:
      context: . 
      dockerfile: Dockerfile
      tags:
        - "fedora-runner"
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    image: fedora-runner
    stdin_open: true  # Keep STDIN open for interactive use
    command: ls -la gen

