version: "3.9"

services:
  runner-task:
    build:
      context: . 
      dockerfile: Dockerfile
      tags:
        - "fedora-runner"
    image: fedora-runner
    stdin_open: true  # Keep STDIN open for interactive use
    # tty: true
    command: python -m grpc_tools.protoc -I./protos/ --python_out=./gen/ --pyi_out=./gen/ --grpc_python_out=./gen/ ./protos/helloworld.proto
    volumes:
      - ./protobuf/gen:/app/gen
